name: Go Install CacheKey PoC

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install golangci-lint
        run: go install -trimpath -buildvcs=false -ldflags="-s -w" github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6
      - name: Run main.go with golangci-lint
        run: go run main.go golangci-lint
